import sys
from config import parse_config, ConfigError, set_42_limits
from algorithms.prim import generate_maze
from typing import List


"""
Maze visualizer for the A-Maze-ing 42 project.

Input: grid generated by `generate_maze()` function
Output: ASCII maze printed to console
"""


# --- Direction constants ---

NORTH = 0  # bit 0 → value 1
EAST  = 1  # bit 1 → value 2
SOUTH = 2  # bit 2 → value 4
WEST  = 3  # bit 3 → value 8

WALL_BITS = {NORTH: 1, EAST: 2, SOUTH: 4, WEST: 8}

def print_ascii_maze(grid: list[list[int]], safe: list[tuple[int,int]]) -> None:
    """
    Print a simple ASCII representation of the maze to the terminal.
    Uses '+', '-', '|' and spaces.
    """
    height = len(grid)
    width = len(grid[0]) if height > 0 else 0

    for r in range(height):
        # Top edge of row
        top = ""
        for c in range(width):
            top += "+"
            top += "--" if (grid[r][c] & WALL_BITS[NORTH]) else "  "
        top += "+"
        print(top)

        # Middle of row
        mid = ""
        for c in range(width):
            mid += "|" if (grid[r][c] & WALL_BITS[WEST]) else " "
            mid += "██" if (r, c) in safe else "  "
            # mid += "  "
        mid += "|" if (grid[r][width - 1] & WALL_BITS[EAST]) else " "
        print(mid)

    # Bottom edge
    bottom = ""
    for c in range(width):
        bottom += "+"
        bottom += "--" if (grid[height - 1][c] & WALL_BITS[SOUTH]) else "  "
    bottom += "+"
    print(bottom)


if __name__ == "__main__":
    try:
        if len(sys.argv) != 2:
            print("Usage: python3 a_maze_ing.py config.txt")
            sys.exit(1)
        file_name = sys.argv[1]
        if not file_name.lower().endswith(".txt"):
            raise ConfigError("file_name must end with .txt")
        config = parse_config(file_name)
        WIDTH = config.width
        HEIGHT = config.height
        ENTRY = config.entry
        EXIT = config.exit_
        PERFECT = config.perfect
        SEED = config.seed
        output_file = config.output_file
        maze = generate_maze(WIDTH, HEIGHT, SEED, PERFECT)
        safe = set_42_limits(WIDTH, HEIGHT)
        print_ascii_maze(maze, safe)


    except Exception as e:
        print(e)