from typing import List, Optional, Any
from dataclasses import dataclass
import random

"""
Maze visualizer for the A-Maze-ing 42 project.

Input: grid generated by `generate_maze()` function
Output: ASCII maze printed to console
"""
@dataclass
class additional:
    path_check: bool
    color_check: bool
    color_42_check: bool


# --- Direction constants ---

NORTH = 0  # bit 0 → value 1
EAST  = 1  # bit 1 → value 2
SOUTH = 2  # bit 2 → value 4
WEST  = 3  # bit 3 → value 8

RESET_CODE = "\033[0m"
RED_CODE = "\033[91m"
GREEN_CODE = "\033[32m"
BLUE_CODE = "\033[34m"
YELLOW_CODE = "\033[33m"
WHITE_CODE = "\033[37m"
MAGENTA_CODE = "\033[35m"
CYAN_CODE = "\033[36m"

colors = [RED_CODE, GREEN_CODE, BLUE_CODE, YELLOW_CODE, WHITE_CODE, MAGENTA_CODE, CYAN_CODE]

WALL_BITS = {NORTH: 1, EAST: 2, SOUTH: 4, WEST: 8}



def print_ascii_maze(
    grid: list[list[int]],
    safe: list[tuple[int, int]],
    add_vars: additional,
    path: Optional[list[tuple[int, int]]] = None
) -> None:
    """
    Print a simple ASCII representation of the maze to the terminal.
    Uses '+', '-', '|' and spaces.
    """
    height = len(grid)
    width = len(grid[0]) if height > 0 else 0
    path_set = set(path) if path else set()
    if add_vars.color_check:
        color = random.choice(colors)
    else:
        color = WHITE_CODE

    if add_vars.color_42_check:
        color_42 = random.choice(colors)
    else:
        color_42 = WHITE_CODE

    for r in range(height):
        # Top edge of row
        top = ""
        for c in range(width):
            top += "+"
            top += "--" if (grid[r][c] & WALL_BITS[NORTH]) else "  "
        top += "+"
        print(color + top)

        # Middle of row
        mid = ""
        for c in range(width):
            mid += "|" if (grid[r][c] & WALL_BITS[WEST]) else " "
            if (r, c) in path_set and add_vars.path_check:
                mid += "🐧"       # path marker, 2 chars wide
            elif (r, c) in safe:
                mid += color_42 + "██" + color       # safe zone, 2 chars wide
            else:
                mid += "  "       # empty cell, 2 chars wide
        mid += "|" if (grid[r][width - 1] & WALL_BITS[EAST]) else " "
        print(mid)

    # Bottom edge
    bottom = ""
    for c in range(width):
        bottom += "+"
        bottom += "--" if (grid[height - 1][c] & WALL_BITS[SOUTH]) else "  "
    bottom += "+"
    print(bottom + RESET_CODE)